### ISSUE TITLE
Events not pulling into UniFi Event Monitor

### ISSUE THREAD

**Issue by santiagon610** [tborychowski/unifi-event-monitor#3]
First and foremost, this is an awesome project, and I'm excited to run it in my environment!

I'm currently running `unifi-event-monitor` in a Kubernetes cluster, and have it pointed to my UniFi Controller on the public Internet.

Looking at the environment vars, the three expected ones from the documentation are there:
```properties
HOST=https://unifi.[redacted]:8443
USERNAME=my-service-account
PASSWORD=[absolutely redacted]
```

And looking at the filesystem within the container, the volume mounts for the other two flat files are present, as well:

_/app/.apprise_
```
slack://[redacted]/[redacted]/[redacted]
```

_/app/blacklist.txt_
```
dummy text to blacklist
ensure that something is in this file and that it is populated
```

Looking at the pod logs, I see the following being sent to `stdout`: 

```
Connected To UniFi Controller
```

But no events make it through to the event monitor, despite being very active within the UniFi Controller, and seeing a number of events enter the pane in the web console over the past hour. A sampling is here:

```
Admin Admin [REDACTED] log in from [PUBLIC IP]	1:15 am	Oct 05 2022	
[SOME SWITCH] was upgraded from "4.0.80.10875" to "6.3.13.14104"	1:10 am	Oct 05 2022	
[MAC ADDRESS] disconnected from [NETWORK NAME] (7m connected, 0 B)	1:07 am	Oct 05 2022	
[MAC ADDRESS] has connected to  with SSID [SSID] on channel 11	1:06 am	Oct 05 2022	
[SOME SWITCH] was scheduled for upgrade by Admin [USERNAME]	1:05 am	Oct 05 2022	
[MAC ADDRESS] disconnected from [SSID] (1h 43m connected, 119 KB, last )	1:05 am	Oct 05 2022	
Admin Admin [REDACTED] log in from [PUBLIC IP]	12:59 am	Oct 05 2022	
```

Looking in the source code, I don't see a method of turning on a debug mode via an environment variable or similar, but am open to suggestions. Any thoughts?

Thanks!

**Comment by tborychowski** [comment]
Thank you for reporting this issue.
I'd love to help you, but (for personal reasons) I don't have enough time to devote to this project.
I may come back to it some day, but cannot say when will that be.
So if it's urgent, you may want to consider alternatives (or try to fix it on your own).
Sorry about that.

**Comment by santiagon610** [comment]
No worries at all. While I'd love to help, I don't quite have the expertise to fix it myself either. Thanks for your response!
